const { createContext } = require("react");

export const BuilderContext = createContext({
  showBuilder: false,
  setShowBuilder: () => {},
  fullName: "",
  setFullName: () => {},
  phoneNumber: "",
  setPhoneNumber: () => {},
  emailAddress: "",
  setEmailAddress: () => {},
  summaryTitle: "",
  setSummaryTitle: () => {},
  summaryDesc: "",
  setSummaryDesc: () => {},
  skillTitle: "",
  setSkillTitle: () => {},
  skillsArr: [],
  setSkillsArr: () => {},
  experienceTitle: "",
  setExperienceTitle: () => {},
  experiencesArr: [],
  setExperiencesArr: () => {},
  educationTitle: "",
  setEducationTitle: () => {},
  educationArr: [],
  setEducationArr: () => {},
  linkedInLink: "",
  setLinkedInLink: () => {},
  portfolioLink: "",
  setPortfolioLink: () => {},
  sectionsArr: [],
  setSectionsArr: () => {},
});
